In [17]:
import numpy as np

# Problem A

In [23]:
np.random.seed(2112) #Setting a seed for the 5x5 array
X = np.random.randint(10, 101, size=(5,5))

X_mean = X.mean() #Solving for mean
X_std = X.std() #Solving for standard deviation
X_normalized = (X - X_mean) / X_std #Solving for normalization of the array

#Displaying array, mean, standard deviation, and normalized array
print("Array:")
print(X)
print("Normalized Array")
print(X_normalized)
print("Mean of X_normalize (should be 0):", X_normalized.mean())
print("Standard Deviation of X_normalize (should be 1):", X_normalized.std())

#Saving the array into a file
np.save('X_normalized.npy', X_normalized)

Array:
[[48 11 15 67 21]
 [11 41 13 66 24]
 [71 79 53 67 70]
 [77 35 91 19 96]
 [35 54 37 41 17]]
Normalized Array
[[ 0.06340841 -1.36714726 -1.2124926   0.79801809 -0.98051059]
 [-1.36714726 -0.20723725 -1.28981993  0.75935442 -0.86451959]
 [ 0.95267275  1.26198209  0.25672675  0.79801809  0.91400909]
 [ 1.18465476 -0.43921926  1.72594609 -1.05783793  1.91926443]
 [-0.43921926  0.29539042 -0.36189192 -0.20723725 -1.13516526]]
Mean of X_normalize (should be 0): 0.0
Standard Deviation of X_normalize (should be 1): 0.9999999999999999


# Problem B

In [24]:
C = (np.arange(1, 101) ** 3).reshape(10, 10) #Creating the first 100 positive integers and cubing them and turning them into a 10x10 array.

divide_by_4 = C[C % 4 == 0] #Specifying cubed integers only divisible by 4 

#Printing array, number of elements, first element, and last element
print("Shape of array C:", C.shape)
print("Array divide_by_4:")
print(divide_by_4)
print("Number of selected elements:", divide_by_4.size)
print("First element:", divide_by_4[0])
print("Last element:", divide_by_4[-1])

#Saving array into a file
np.save('div_by_4.npy', divide_by_4)

Shape of array C: (10, 10)
Array divide_by_4:
[      8      64     216     512    1000    1728    2744    4096    5832
    8000   10648   13824   17576   21952   27000   32768   39304   46656
   54872   64000   74088   85184   97336  110592  125000  140608  157464
  175616  195112  216000  238328  262144  287496  314432  343000  373248
  405224  438976  474552  512000  551368  592704  636056  681472  729000
  778688  830584  884736  941192 1000000]
Number of selected elements: 50
First element: 8
Last element: 1000000


# Problem C

In [22]:
S = (np.arange(1, 37) ** 2).reshape(6, 6) #Creating a 6x6 array with the square of the first 36 positive integers.

S_mean = S.mean() #Mean of array

above_mean = S[S > S_mean] #Integers that are only above the mean

#Printing array, mean, integers above the mean, number of selected integers, first element, and last element.
print("Array S:")
print(S)
print("\nMean of S (S_mean):", S_mean)
print("\nArray above_mean:")
print(above_mean)
print("\nNumber of selected elements:", above_mean.size)
print("First element:", above_mean[0])
print("Last element:", above_mean[-1])

# Saving array into a file
np.save('above_mean.npy', above_mean)

Array S:
[[   1    4    9   16   25   36]
 [  49   64   81  100  121  144]
 [ 169  196  225  256  289  324]
 [ 361  400  441  484  529  576]
 [ 625  676  729  784  841  900]
 [ 961 1024 1089 1156 1225 1296]]

Mean of S (S_mean): 450.1666666666667

Array above_mean:
[ 484  529  576  625  676  729  784  841  900  961 1024 1089 1156 1225
 1296]

Number of selected elements: 15
First element: 484
Last element: 1296
